Repository hmcts/hmc-hmi-inbound-adapter, pull requests merged in 2021-12, with the labels that each got.

#20 CCD-2312: Temporarily disable Fortify Scan in nightly build
  Jenkinsfile_nightly
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-20

#21 update log4j
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-21

#22 CCD-2351: Update log4j version to 2.16.0
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-22

#23 CCD-2374: Update log4j version to 2.17.0
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-23
