Repository hmcts/hmc-hmi-inbound-adapter, pull requests merged in 2021-07, with the labels that each got.

#4 suppression of CVEs
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-4

#2 HMAN-16
  Jenkinsfile_CNP
  README.md
  build.gradle
  charts/hmc-hmi-inbound-adapter/Chart.yaml
  charts/hmc-hmi-inbound-adapter/values.preview.template.yaml
  charts/hmc-hmi-inbound-adapter/values.yaml
  config/owasp/suppressions.xml
  lombok.config
  src/functionalTest/java/uk/gov/hmcts/reform/hmc/hmi/befta/EmptySmokeTest.java
  src/functionalTest/resources/features/F-000/S-000.td.json
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/BaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/WiremockFixtures.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/MessageSenderConfigurationIT.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/GetWelcomeTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HmcInboundControllerIT.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceIT.java
  src/integrationTest/resources/application-itest.yaml
  src/main/java/uk/gov/hmcts/reform/hmc/ApplicationParams.java
  src/main/java/uk/gov/hmcts/reform/hmc/RestTemplateConfiguration.java
  src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/ErrorDetails.java
  src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/Hearing.java
  src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/HearingDetailsRequest.java
  src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/HearingResponse.java
  src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/MetaResponse.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/MessageSenderConfiguration.java
  src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
  src/main/java/uk/gov/hmcts/reform/hmc/controllers/HmcInboundController.java
  src/main/java/uk/gov/hmcts/reform/hmc/exceptions/ApiError.java
  src/main/java/uk/gov/hmcts/reform/hmc/exceptions/BadRequestException.java
  src/main/java/uk/gov/hmcts/reform/hmc/exceptions/ResourceNotFoundException.java
  src/main/java/uk/gov/hmcts/reform/hmc/exceptions/RestExceptionHandler.java
  src/main/java/uk/gov/hmcts/reform/hmc/exceptions/ServiceException.java
  src/main/java/uk/gov/hmcts/reform/hmc/exceptions/ValidationError.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/CftHearingService.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/CftHearingServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementService.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/common/DefaultObjectMapperService.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/common/ObjectMapperService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/hmc/ApplicationParamsTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/controllers/HmcInboundControllerTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/CftHearingServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/common/DefaultObjectMapperServiceTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/utils/TestingUtil.java
  src/test/java/uk/gov/hmcts/reform/rsecheck/DemoUnitTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-2

#7 Fix master pipeline
  charts/hmc-hmi-inbound-adapter/Chart.yaml
  charts/hmc-hmi-inbound-adapter/values.yaml
  src/main/resources/application.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-7

#5 fix all CVEs in the repo
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-5

#8 fix for CVE-2021-33037
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-8

#6 CCD-1604 : Fortify Scan implementation for HMI Inbound Adapter
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-6
