Repository hmcts/hmc-hmi-inbound-adapter, pull requests merged in 2021-11, with the labels that each got.

#14 CCD-2122: Address CVE-2021-42340
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-14

#15 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-15

#16 CCD-2144: Address CVE-2021-22096
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-16

#17 Update Jenkinsfile_CNP sync branches
  Jenkinsfile_CNP
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-17

#18 CCD-2121: Address CVE-2021-37136 and CVE-2021-37137
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-18
