Repository hmcts/hmc-hmi-inbound-adapter, pull requests merged in 2022-06, with the labels that each got.

#78 HMAN-254 - improve code coverage and sonar issues
  build.gradle
  src/main/java/uk/gov/hmcts/reform/hmc/exceptions/ServiceException.java
  src/main/java/uk/gov/hmcts/reform/hmc/validator/HearingCodeEnumPattern.java
  src/main/java/uk/gov/hmcts/reform/hmc/validator/HearingCodeEnumPatternValidator.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImplTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-78

#73 Update azure-messaging-servicebus to latest
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-73

#81 Remove non-required scope prior to go live
  src/main/resources/application.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-81

#82 Add custom APIM name suffix for perftest
  infrastructure/perftest.tfvars
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-82

#83 Ccd 3262 fortify docker uses root user
  Dockerfile
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-83

#79 CCD-3283: Add ARGs for builder stage paths to Dockerfile
  Dockerfile
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-79

#84 CCD-3387 Remove CVE Suppress Until Date from All Services
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-84

#85 CCD-3248 Monthly Review of All Security Flags - Commented out all sup…
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-85

#87 CCD-3248 Monthly Review of All Security Flags - All suppressions comm…
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-87
