Repository hmcts/hmc-hmi-inbound-adapter, pull requests merged in 2022-12, with the labels that each got.

#118 CCD-4043 Fasterxml Jackson Upgrade
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-118

#119 HMAN-492 CVE-2021-37533 Suppression
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-119

#117 CCD-4050: Fix Jenkins pipeline warnings
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-117

#122 HMAN-497 CVE-2022-41881 Suppression
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-122

#123 CVE suppression
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-123
