Repository hmcts/hmc-hmi-inbound-adapter, pull requests merged in 2022-05, with the labels that each got.

#57 HMAN-171 - Error if hearingVenue.locationReferences.key != to EPIMS
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HmcInboundControllerIT.java
  src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/Hearing.java
  src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/HearingVenue.java
  src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/hmc/controllers/HmcInboundControllerTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/utils/TestingUtil.java
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-57

#51 HMAN-144 [PUT Hearing response] Add validation around hearingCaseVersionId
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/WiremockFixtures.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HmcInboundControllerIT.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceIT.java
  src/main/java/uk/gov/hmcts/reform/hmc/Application.java
  src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/CftHearingService.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/CftHearingServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/CftHearingServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImplTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-51

#61 CCD-3121: CVE-2022-22968: hmc-hmi-inbound-adaptor fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-61

#70 suppression for CVE-2022-24823
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-70

#68 Updated wiremock to 2.33.2, remove suppression CVE-2020-11022
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-68

#71 CVE-2022-24823 : hmc-hmi-inbound-adapter fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-71

#72 until_date_extension_for_current_CVEs
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-72

#74 suppression of CVE-2022-29885
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-74

#52 HMAN-162 Amend PUT /listings/{id}
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/Hearing.java
  src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/HearingSession.java
  src/test/java/uk/gov/hmcts/reform/hmc/utils/TestingUtil.java
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-52

#76 HMAN-256 - fix field names for hearingAttendees and hearingJohs
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/hmc/client/model/hmi/HearingSession.java
  src/test/java/uk/gov/hmcts/reform/hmc/utils/TestingUtil.java
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-76
