Repository hmcts/hmc-hmi-inbound-adapter, pull requests merged in 2023-10, with the labels that each got.

#154 CCD-4845: Renovate config
  .dependabot/config.yml
  .github/renovate.json
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-154

#153 HMAN-573 : Terminal State - Ignore List Assist
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/WiremockFixtures.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HmcInboundControllerIT.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceIT.java
  src/integrationTest/resources/application-itest.yaml
  src/main/java/uk/gov/hmcts/reform/hmc/ApplicationParams.java
  src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/CftHearingService.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/CftHearingServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImpl.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/hmc/ApplicationParamsTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/CftHearingServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImplTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-153

#160 CCD-4949:-CCD-4949
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-160
