Repository hmcts/hmc-hmi-inbound-adapter, pull requests merged in 2023-02, with the labels that each got.

#130 HMAN-515 Bump rse-gradle plugin to add dependency-check v8.0.2
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-130

#131 HMAN-518 Upgrade base charts
  charts/hmc-hmi-inbound-adapter/Chart.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-131

#129 HMAN-509 Remove discoveryComposite from health endpoint
  src/functionalTest/resources/features/F-000/S-000.td.json
  src/main/resources/application.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-129

#133 HMAN-497: Fix CVE-2022-41881 and CVE-2022-41915
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-133
