Repository hmcts/hmc-hmi-inbound-adapter, pull requests merged in 2023-01, with the labels that each got.

#124 HMAN-500 CVE-2021-4277 Suppression
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-124

#121 HMAN-494 Add suppressCves task
  .github/workflows/dependency-check.yml
  build.gradle
  gradle/suppress.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-121

#125 HMAN-501: Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-125

#126 HMAN-502 Bump rse-gradle-java-plugin version
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-126

#127 HMAN-506 : Updated Apache Tomcat to 9.0.69 and moved temporary suppressions to false positives
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-127

#128 Update Chart.yaml
  charts/hmc-hmi-inbound-adapter/Chart.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-128
