Repository hmcts/hmc-hmi-inbound-adapter, pull requests merged in 2023-03, with the labels that each got.

#134 CCD-4396 : Create .terraform-version
  infrastructure/.terraform-version
Labels: ns:hmc, prd:hmc, add-or-update, rel:hmc-hmi-inbound-adapter-pr-134

#136 HMAN-524 Upgrade dependencies to resolve CVE-2023-24998
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-136

#135 update befta-fw version to 8.7.11
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-135
