Repository hmcts/hmc-hmi-inbound-adapter, pull requests merged in 2023-11, with the labels that each got.

#152 HMAN-576 Fix CVE-2023-34035. Upgrade spring-security 5.8.3 to 5.8.7.
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-152

#161 CCD-4771 : Fix CVE-2023-3511
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-161

#163 CCD-4994 : Fix-CVE-2023-36478
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-163

#165 HMAN-602 : Add retries to all acb.tpl.yaml entries
  acb.tpl.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-165

#167 CCD-5066 : Fix broken master pipeline due to CVE clash between DBs
  .github/workflows/dependency-check.yml
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-167

#166 Remove keep:true acb config
  acb.tpl.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-166
