Repository hmcts/hmc-hmi-inbound-adapter, pull requests merged in 2024-04, with the labels that each got.

#182 HMAN-659 Remove CVE-2023-35116 suppression
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-182

#179 HMAN-658
  Dockerfile
  README.md
  build.gradle
  charts/hmc-hmi-inbound-adapter/Chart.yaml
  charts/hmc-hmi-inbound-adapter/values.preview.template.yaml
  charts/hmc-hmi-inbound-adapter/values.yaml
  infrastructure/apps-insight.tf
  lib/applicationinsights.json
  src/main/java/uk/gov/hmcts/reform/AppInsights.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/AppInsightsConfiguration.java
  src/test/java/uk/gov/hmcts/reform/AppInsightsTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-179, aat/add-or-update

#184 HMAN-679 fix CVE-2023-44487
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-184

#187 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-187

#185 HMAN-680 fix CVE-2023-6378
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-185

#183 HMAN-668 PI33 Helm chart upgrade - chart-java
  charts/hmc-hmi-inbound-adapter/Chart.yaml
  charts/hmc-hmi-inbound-adapter/values.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-183

#189 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-189
