Repository hmcts/hmc-hmi-inbound-adapter, pull requests merged in 2024-02, with the labels that each got.

#172 HMAN-608
  build.gradle
  config/checkstyle/checkstyle.xml
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-172

#174 HMAN-528-snakeyaml
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-174

#173 CCD-5024 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-inbound-adapter-pr-173
